### ISSUE TITLE
bug: Viper doesn't read out ns_startup_args.txt

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#92] opened 2022-03-08 22:35 UTC
**Describe the bug**
Technically not so much a bug as unexpected behaviour from a user's perspective. For a while now I was wondering why when launching Northstar from Viper would reset my `ns_startup_args.txt` even without an update pending.
(I usually launch Northstar via the Launcher executable)

Turns out Viper stores the state of the startup args in it's own storage (I think) and overwrites `ns_startup_args.txt` on launch / when saving settings.

This is problematic when a user manually edits `ns_startup_args.txt`, as then launching Nortstar with Viper wipes the made changes. When opening the settings, Viper should read out the contents of `ns_startup_args.txt` and display those. 

**To Reproduce**
1. Edit `ns_startup_args.txt`
2. Launch Viper and go to settings
3. _Launch options_ still shows the old options.
4. Go back out and launch game
5. Launch options displayed in Viper are used
6. Check `ns_startup_args.txt`, file was reset to state displayed in Viper

**Expected behavior**
Viper should read out `ns_startup_args.txt` when opening settings instead of relying on its own internal save.

**Screenshots**
_None_

**Version:**
`v1.2.4`

**Additional Info**
_None_

**Comment by 0neGal** [comment] 2022-03-08 22:41
This was actually originally noted down in the release:

> Your launch arguments may or may not be reset when first launching Viper after the update.

And yes it is a bug, however the majority of the people using Viper won't edit the startup args separate to Viper, and so I sort of disregarded it, because in my head it would only be a problem for the initial startup after the new release, but nope, it's just every time you edit it outside of Viper then launch Viper.

The reason it happens is because of the fact that we still have to have default startup args, this can be worked around, it was just a quick and dirty solution for the time being, I'll have a look at it when I got the time, possibly tomorrow.

**Comment by 0neGal** [comment] 2022-03-09 22:37
Ideally #93 should fix this, however I did brief testing only, if you were to edit the nsargs while Viper is running it'll still set them to what Viper thinks is the correct one. But I don't think that's all a big problem. And I haven't found the exact steps to reproduce, I simply wanted to get a PR up, and if you're able to test it that'd be lovely...

I'll also try testing it further tomorrow...

**Comment by 0neGal** [comment] 2022-03-10 19:18
Did some extra testing, and it seems to work just fine, so I'll merge it and close this issue :)

**Closed** 2022-03-10 19:18 UTC
Labels: bug

**Comment by GeckoEidechse** [comment] 2022-03-12 20:38
Also just remembered that with the next release with `v1.6.0` Northstar will try to register a URI handler for `northstar://` URIs and if denied Northstar will add a launch arg to `ns_startup_args.txt` to prevent re-asking for registering the handler.

So, uhm, good thing this Viper issue was fixed in time ^^

**Comment by 0neGal** [comment] 2022-03-12 20:40
Very much so, what is this handler meant for? Click to join servers or?

**Comment by GeckoEidechse** [comment] 2022-03-12 20:41
Exactly

**Comment by GeckoEidechse** [comment] 2022-03-12 20:42
Basically yeah. Click a `northstar://<some server id, dunno the exact format>` link and you join that server.

c.f.:
- https://github.com/R2Northstar/NorthstarLauncher/pull/104
- https://github.com/R2Northstar/NorthstarMods/pull/259
