### ISSUE TITLE
bug: LSX Failing launching Northstar (Steam)

### ISSUE THREAD

**Issue by angrydestreyer9** [0neGal/viper#136] opened 2022-07-02 03:43 UTC
steam uses its own version of origin when launching ea games as far as i can tell and it seems like viper is trying to access the standard origin client\
![Screenshot 2022-07-01 204114](https://user-images.githubusercontent.com/106773152/176985351-5703180f-6eb7-465f-a93f-d1c4c8374138.png)

**Comment by 0neGal** [comment] 2022-07-02 08:44
Viper on Windows doesn't actually launch Origin at any point, or well, it doesn't do it by itself, it simply finds and runs `Titanfall2.exe -northstar` which then launches Origin first and then Northstar.

As for the error, I'm not entirely sure what's wrong, you could try launching the Origin client first then the game, however I've no clue where Steam stores Origin.

Perhaps @GeckoEidechse can help a little bit more with this since I assume they know a little bit more about what exactly the error means and ways to fix it.

**Comment by GeckoEidechse** [comment] 2022-07-02 10:28
Yeah, LSX error is caused by Titanfall2 failing to communicated with Origin. The solution is to launch Origin manually before launching Northstar. Even if you're on the Steam version it still needs Origin and if I'm not mistaken even if you bought the game on Steam it should've installed Origin when you installed Titanfall2 / launched it for the first time.

Northstar wiki entry in regards to that error message: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#lsx

**Comment by 0neGal** [comment] 2022-07-02 13:58
Given that the only real fix we can do on Viper's end would be to launch Origin, and somehow detect when it was launched, and then launch the game, there's not much we can do. As that would be complicated, to begin with just finding the location of `Origin.exe` and so on.

So I'll be closing this issue...

**Closed by 0neGal** 2022-07-02 13:58 UTC
Labels: bug
