### ISSUE TITLE
bug: Viper launches but shows no window

### ISSUE THREAD

**Issue by Lizbat** [0neGal/viper#231] opened 2024-04-30 05:47 UTC
**Describe the bug**
When I try to launch Viper, it only shows as a background program/process in Task Manager.

**Screenshots**
If I look at Viper in Task Manager, all I can see is this 
![image](https://github.com/0neGal/viper/assets/168512737/34836d28-81ed-4546-be59-907e4b0559a1)

**Version:**
If possible add on `--version` or simply the version of Viper
I used the 1.11.0 Setup Wizard

**Additional Info**
Any extra info should go here!
I recently did a factory reset on my computer, and I'm not sure if that might have something to do with it

**Comment by Lizbat** [comment] 2024-04-30 17:39
(replaced my name with user)
C:\Users\USER>
Checking for update
[4608:0430/143835.151:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[4608:0430/143835.156:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[4608:0430/143835.162:ERROR:disk_cache.cc(208)] Unable to create cache
[4608:0430/143835.162:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
[4608:0430/143835.162:ERROR:disk_cache.cc(208)] Unable to create cache
[4608:0430/143835.162:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
[7644:0430/143835.595:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[7644:0430/143835.603:ERROR:disk_cache.cc(208)] Unable to create cache
Northstar is not installed!
Update for version 1.11.0 is not available (latest version: 1.11.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
(node:4608) UnhandledPromiseRejectionWarning: TypeError: win is not a function
    at gamepath.set (C:\Users\ethan\AppData\Local\Programs\viper\resources\app.asar\src\modules\gamepath.js:156:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `Viper --trace-warnings ...` to show where the warning was created)
(node:4608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by 0neGal** [comment] 2024-04-30 18:53
I'll be entirely honest and say that I have utterly no clue how this error is even possible, it's complaining a module that a module exported something that wasn't a function when trying to run it as such, even though said module never exports anything but a module, possibly a very weird race condition? No clue...

Does this happen 100% of the time you launch Viper? And can you check if it also happens with/in the [portable `.exe`](https://0negal.github.io/viper/?win-portable)?

**Comment by 0neGal** [comment] 2024-04-30 19:30
Hmm, I can reproduce the error now, I'll report back once I debug this a bit...

**Comment by 0neGal** [comment] 2024-04-30 19:39
Okay, spent a bit, found a fix, then spent like 5 minute attempting to understand why it fixes it, and how the issue even occurred, turns out, I just did an oopsie brainfart.

This should be fixed in upstream, aka in the next release, I'll attempt to get it out later today or similar...

**Closed** 2024-04-30 19:39 UTC
Labels: bug

**Comment by 0neGal** [comment] 2024-04-30 19:56
Just for the sake of confirming, there's some upstream builds available for Windows [here](https://github.com/0neGal/viper/actions/runs/8900636224/artifacts/1461882013), if you're able to download it and test if the portable `.exe` functions, then that'd be perfect.

**Comment by Lizbat** [comment] 2024-04-30 20:36
I'll give it a look and let you know what happens!

**Comment by Lizbat** [comment] 2024-04-30 20:38
Okay, I tried the standalone .exe and the same thing happened, it launched but there's no window and it is showing in background processes

**Comment by 0neGal** [comment] 2024-04-30 20:42
Huh, can you check if the logs are any different?

**Comment by Lizbat** [comment] 2024-04-30 20:45
How would I check the logs? Would it just be putting the file into cmd or Powershell?

**Comment by 0neGal** [comment] 2024-04-30 20:46
Correct yes, as before, sorry for not clarifying...

**Comment by Lizbat** [comment] 2024-04-30 20:49
I put it into cmd and it came back with this 
![image](https://github.com/0neGal/viper/assets/168512737/2f09a473-95af-4342-8958-daa888c02fa1)

**Comment by Lizbat** [comment] 2024-04-30 20:49
I got the game location and it launched!

**Comment by 0neGal** [comment] 2024-04-30 20:50
Well that's great, but weird lol, are you sure you ran the correct/new `.exe` before? :p

**Comment by Lizbat** [comment] 2024-04-30 20:51
I'm sure! Let me try it again to make sure though

**Comment by Lizbat** [comment] 2024-04-30 20:52
Woaw, it launched this time, maybe because I set the path

**Comment by 0neGal** [comment] 2024-04-30 20:53
You can also delete the `viper.json` file in `%APPDATA%` to reset/delete the config file
