### ISSUE TITLE
Viper on SteamDeck cannot locate Titanfall if it is installed on an SD card

### ISSUE THREAD

**Issue by Taskie16** [0neGal/viper#149] opened 2022-08-31 23:55 UTC
On Steam deck if Viper cant locate the Titanfall files automatically, the file browser that is used to manually select the Titanfall files cant search files downloaded to a micro sd card (as far as I am awear). The manual selector can only choose from files on the steam deck's internal hard drive, but on a 64 gb the game has to be downloaded on a micro sd. This may be due to the files selector though.

**Comment by GeckoEidechse** [comment] 2022-08-31 23:58
Are you using the Viper Flatpak from the Discover Software store?

**Comment by Taskie16** [comment] 2022-09-01 00:04
Yes

**Comment by GeckoEidechse** [comment] 2022-09-01 00:08
This issue might be specific to the Flatpak version, i.e. https://github.com/flathub/com.github._0negal.Viper

If you wanna help in figuring out whether the issue is with Flatpak or Viper in general, download the AppImage version of Viper [from the newest release](https://github.com/0neGal/viper/releases), run it, and see if you can select the folder.
If yes, then the issue is Flatpak specific, if no, then the issue is with Viper in general.

**Comment by GeckoEidechse** [comment] 2022-09-01 00:22
Aight, issue is Flatpak specific then

@0neGal do you have enough rights to transfer this issue over or should I make a new issue in https://github.com/flathub/com.github._0negal.Viper ? ^^

**Comment by Taskie16** [comment] 2022-09-01 00:27
Do you want me to close the issue?

**Comment by GeckoEidechse** [comment] 2022-09-01 00:29
> Do you want me to close the issue?

eh, keep it open for now in case it gets transferred ^^

**Comment by Taskie16** [comment] 2022-09-01 00:30
ok will do

**Comment by 0neGal** [comment] 2022-09-01 05:48
> @0neGal do you have enough rights to transfer this issue over or should I make a new issue in https://github.com/flathub/com.github._0negal.Viper ? ^^

I do not nope... :p

**Comment by GeckoEidechse** [comment] 2022-09-01 11:35
> > @0neGal do you have enough rights to transfer this issue over or should I make a new issue in https://github.com/flathub/com.github._0negal.Viper ? ^^
> 
> I do not nope... :p

Aight, I made https://github.com/flathub/com.github._0negal.Viper/issues/5 now, so you can close this issue here ^^

**Closed** 2022-09-01 11:36 UTC
Labels: bug
