### ISSUE TITLE
bug: Northstar not auto updating

### ISSUE THREAD

**Issue by Enthusiest** [0neGal/viper#166] opened 2023-01-08 05:55 UTC
**Describe the bug**
Viper is not auto updating the Northstar Client

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/122195601/211182606-598b4b9b-0fcc-4bb2-bf99-528217bc3cf1.png)
It should be 1.11.4 and not 1.11.1

**Version:**
If possible add on `--version` or simply the version of Viper
1.11.1
**Additional Info**
Any extra info should go here!

**Comment by 0neGal** [comment] 2023-01-08 15:16
Viper checks for updates every so often (every 15min), however as to not spam and get blocked by GitHub it caches and saves what the latest version is.

This cache is only considered invalid after a certain amount of time has passed (5min) since the cache was made, meaning if you continuously click "Check for updates", nothing will really be checked for except whether the installed version is that of the cached version.

If you could retry checking for updates now, since enough time has passed, and confirm that it does install the newest update.

**Comment by 0neGal** [comment] 2023-01-12 18:37
As there's been no answer here, and this isn't very reproducible (no to mention my proposed solution and explanation likely being the answer), I'll be closing this issue, feel free to open it, if your problem still exists.

**Closed by 0neGal** 2023-01-12 18:37 UTC
Labels: bug
